### ISSUE TITLE
VSCode search hightlight isn't clear.

### ISSUE THREAD

**Issue by rockmandash** [cevr/overnight#2]
![image](https://user-images.githubusercontent.com/7580792/75236520-ded18380-57f8-11ea-9987-e53fb0b367c6.png)

There is no way to see hightlighted target.

**Comment by cevr** [comment]
Hi!

Do you mean when the text is highlighted and there is a search match?

**Comment by rockmandash** [comment]
Yes, the highlighted color is the same as background color, so there is no way to see the highlighted text.

**Comment by cevr** [comment]
Thanks for making an issue! I'll see if I can fix that ASAP.

**Comment by cevr** [comment]
Just published 1.7.3!

Match highlighting and selection highlighting are now different in the Overnight Slumber themes
